<repl> ::= <command> | <command> <repl>

<command> ::= <add_command> | <list_command> | <remove_command> | <quit_command>

<add_command> ::= "add" <car> ("," <car>)*

<list_command> ::= "list"

<remove_command> ::= "remove" <id>

<quit_command> ::= "quit"

<car> ::= <make> <model> <year>

<make> ::= <string>

<model> ::= <string>

<year> ::= <number>

<id> ::= <number>

<string> ::= <char>+
<char> ::= 'a' | 'b' | 'c' | ... | 'z' | 'A' | 'B' | ... | 'Z' | '0' | '1' | ... | '9' | ' '

<number> ::= <digit>+
<digit> ::= '0' | '1' | '2' | ... | '9'
